/* tslint:disable */
import { GraphQLResolveInfo } from 'graphql';
/**
 * This file is auto-generated by graphql-schema-typescript
 * Please note that any changes in this file may be overwritten
 */
 

/*******************************
 *                             *
 *          TYPE DEFS          *
 *                             *
 *******************************/
export interface GQLQuery {
  accounts?: Array<GQLAccount | null>;
  account?: GQLAccount;
  categories?: Array<GQLCategory | null>;
  category?: GQLCategory;
}

export interface GQLAccount {
  id?: string;
  accountName?: string;
  institutionId?: string;
  institution?: GQLInstitution;
  balance?: number;
}

export interface GQLInstitution {
  name?: string;
}

export interface GQLCategory {
  name?: string;
  root_accounts?: Array<GQLAccount | null>;
}

/*********************************
 *                               *
 *         TYPE RESOLVERS        *
 *                               *
 *********************************/
/**
 * This interface define the shape of your resolver
 * Note that this type is designed to be compatible with graphql-tools resolvers
 * However, you can still use other generated interfaces to make your resolver type-safed
 */
export interface GQLResolver {
  Query?: GQLQueryTypeResolver;
  Account?: GQLAccountTypeResolver;
  Institution?: GQLInstitutionTypeResolver;
  Category?: GQLCategoryTypeResolver;
}
export interface GQLQueryTypeResolver<TParent = any> {
  accounts?: QueryToAccountsResolver<TParent>;
  account?: QueryToAccountResolver<TParent>;
  categories?: QueryToCategoriesResolver<TParent>;
  category?: QueryToCategoryResolver<TParent>;
}

export interface QueryToAccountsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QueryToAccountArgs {
  id: string;
}
export interface QueryToAccountResolver<TParent = any, TResult = any> {
  (parent: TParent, args: QueryToAccountArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QueryToCategoriesResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QueryToCategoryArgs {
  name: string;
}
export interface QueryToCategoryResolver<TParent = any, TResult = any> {
  (parent: TParent, args: QueryToCategoryArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLAccountTypeResolver<TParent = any> {
  id?: AccountToIdResolver<TParent>;
  accountName?: AccountToAccountNameResolver<TParent>;
  institutionId?: AccountToInstitutionIdResolver<TParent>;
  institution?: AccountToInstitutionResolver<TParent>;
  balance?: AccountToBalanceResolver<TParent>;
}

export interface AccountToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface AccountToAccountNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface AccountToInstitutionIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface AccountToInstitutionResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface AccountToBalanceArgs {
  date?: string;
}
export interface AccountToBalanceResolver<TParent = any, TResult = any> {
  (parent: TParent, args: AccountToBalanceArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLInstitutionTypeResolver<TParent = any> {
  name?: InstitutionToNameResolver<TParent>;
}

export interface InstitutionToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLCategoryTypeResolver<TParent = any> {
  name?: CategoryToNameResolver<TParent>;
  root_accounts?: CategoryToRoot_accountsResolver<TParent>;
}

export interface CategoryToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface CategoryToRoot_accountsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}
